email: bulanva@internet.ru
file_storage_directory: C:/proect/
from: 82
imap: imap.mail.ru:993
last_uid: <CAPT3h_gzaPwJXVs6c30QX9oWHvPBCg25mKakANBPPNQKsjRO=g@mail.gmail.com>
password: QLQgCWrcCCwUz1RGdxqb
