email: bulanva@internet.ru
file_storage_directory: C:/proect/
from: 72
imap: imap.mail.ru:993
last_uid: <CAPT3h_hsdY2_gcYTta=cEQtJDvop06qg5tiHOG9cEwugk-Ldgg@mail.gmail.com>
password: QLQgCWrcCCwUz1RGdxqb
pathsave: ./
